import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/components/ThemeProvided";
import { SideNav, SideNavData, SideNavTypes } from "@/components/layout/sidenav";

import NextTopLoader from 'nextjs-toploader';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={` ${inter.className} flex flex-row`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange>
          <SideNav />
          <main>
            <NextTopLoader
              color="#2563EB"
              showSpinner={false}
            />
            {children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
